"""
Django settings for src project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

load_dotenv(override=True)


BASE_DIR = Path(__file__).resolve().parent.parent

SAMESITE = "None"

SECRET_KEY = os.getenv("SECRET_KEY", "insecure-demo-secret-key")

DEBUG = os.getenv("DEBUG", "true").lower() == "true"

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",
    "corsheaders",
    "rest_framework",
    "rest_framework_simplejwt.token_blacklist",
    "channels",
    "src",
    "auth_api",
    "mail",
    "quiz",
    "ai",
]

DISABLE_CSRF = os.getenv("DISABLE_CSRF", "true").lower() == "true"

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "auth_api.middleware.CSRFMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

if DISABLE_CSRF:
    MIDDLEWARE = [
        middleware
        for middleware in MIDDLEWARE
        if middleware != "django.middleware.csrf.CsrfViewMiddleware"
    ]

ROOT_URLCONF = "src.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": ["templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "src.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.config(
        default=os.environ.get(
            "DATABASE_URL", "postgres://user:password@localhost:5432/mydjangodb"
        ),
        conn_max_age=600,
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

REST_FRAMEWORK = {
    "EXCEPTION_HANDLER": "src.exception_handler.custom_exception_handler",
    "DEFAULT_RENDERER_CLASSES": [
        "src.renderers.CustomJSONRenderer",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "auth_api.authenticate.CustomAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
}


# JWT / Cookie
SIMPLE_JWT = {
    # The lifetime of the access token. After this period, the token will expire.
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=1),
    # The lifetime of the refresh token. Used to obtain new access tokens.
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    # Whether to rotate refresh tokens on each use. If True, a new refresh token is issued with each access token refresh.
    "ROTATE_REFRESH_TOKENS": True,
    # Whether to blacklist refresh tokens after rotation. Ensures the old refresh token cannot be used.
    "BLACKLIST_AFTER_ROTATION": True,
    # Whether to update the last login timestamp on token refresh. If False, last login time is not updated.
    "UPDATE_LAST_LOGIN": False,
    # The algorithm used for signing tokens. HS256 is a common choice.
    "ALGORITHM": "HS256",
    # The key used to sign the tokens. Must be kept secret.
    "SIGNING_KEY": SECRET_KEY,
    # The key used to verify the tokens. Typically set to None when using a signing key.
    "VERIFYING_KEY": None,
    # Optional audience claim for token verification. Set to None if not used.
    "AUDIENCE": None,
    # Optional issuer claim for token verification. Set to None if not used.
    "ISSUER": None,
    # URL for JSON Web Key Set (JWK). Set to None if not using JWK.
    "JWK_URL": None,
    # The amount of time, in seconds, that the token's expiration time is allowed to differ from the current time.
    "LEEWAY": 0,
    # The type of authorization header to use. Commonly 'Bearer'.
    "AUTH_HEADER_TYPES": ("Bearer",),
    # The name of the HTTP header that will contain the token. Default is 'Authorization'.
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    # The authentication rule used to authenticate the user. Default is a standard rule.
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",
    # The classes of tokens that can be used. Default includes access tokens.
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    # The claim in the token that indicates the type of token (access or refresh).
    "TOKEN_TYPE_CLAIM": "token_type",
    # The class used to represent the user in the token. Default is 'TokenUser'.
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",
    # The claim used to store the token's unique identifier.
    "JTI_CLAIM": "jti",
    # The claim in the sliding token that indicates the expiration time of the refresh token.
    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    # The lifetime of the sliding token, after which it expires. Sliding tokens provide more flexibility in session length.
    "SLIDING_TOKEN_LIFETIME": timedelta(minutes=5),
    # The lifetime of the sliding token's refresh period.
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=1),
    # Custom cookie settings for authentication tokens.
    "AUTH_COOKIE": "access",  # Name of the cookie that holds the access token.
    # Name of the cookie that holds the refresh token.
    "AUTH_COOKIE_REFRESH": "refresh",
    # Domain for the auth cookies. Set to None for the standard domain.
    "AUTH_COOKIE_DOMAIN": None,
    # Whether to use secure cookies (only transmitted over HTTPS). True for secure cookies.
    "AUTH_COOKIE_SECURE": True,
    # HttpOnly flag for cookies. When set to True, the cookie cannot be accessed via JavaScript.
    "AUTH_COOKIE_HTTP_ONLY": True,
    # Path for which the cookies are valid. Default is the root of the domain.
    "AUTH_COOKIE_PATH": "/",
    # SameSite attribute for cookies. Determines how cookies are sent with cross-site requests.
    "AUTH_COOKIE_SAMESITE": SAMESITE,
    "TOKEN_OBTAIN_SERIALIZER": "auth_api.serializers.CustomTokenObtainPairSerializer",
}

AUTHENTICATION_BACKENDS = [
    "auth_api.backends.UsernameOrEmailBackend",
    "django.contrib.auth.backends.ModelBackend",
]

AUTH_USER_MODEL = "auth_api.User"


LOGGING_DIR = os.path.join(BASE_DIR, "logs")
os.makedirs(LOGGING_DIR, exist_ok=True)
if not DEBUG:
    LOGGING = {
        "version": 1,
        "disable_existing_loggers": False,
        "root": {
            "level": "INFO",
            "handlers": ["file"],
        },
        "formatters": {
            "verbose": {
                "format": "%(levelname)s %(asctime)s %(module)s "
                "%(process)d %(thread)d %(message)s"
            },
        },
        "handlers": {
            "file": {
                "level": "INFO",
                "class": "logging.FileHandler",
                "filename": os.path.join(LOGGING_DIR, "django.log"),
                "formatter": "verbose",
            },
        },
        "loggers": {
            "django": {
                "level": "INFO",
                "handlers": ["file"],
                "propagate": False,
            },
            "django.db.backends": {
                "level": "INFO",
                "handlers": ["file"],
                "propagate": False,
            },
            "django.security.DisallowedHost": {
                "level": "INFO",
                "handlers": ["file"],
                "propagate": False,
            },
            "project": {
                "level": "INFO",
                "handlers": ["file"],
                "propagate": False,
            },
        },
    }


SMTP_SERVER = os.getenv("SMTP_SERVER")
SMTP_PORT = os.getenv("SMTP_PORT")
SENDER_EMAIL = os.getenv("SENDER_EMAIL")
SENDER_PASSWORD = os.getenv("SENDER_PASSWORD")


FRONTEND_URL = os.getenv("FRONTEND_URL")
SITE_DOMAIN = FRONTEND_URL

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media_files")


if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = False

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOWED_STR = os.getenv("CORS_ALLOWED")
CORS_ALLOW_CREDENTIALS = True

if CORS_ALLOWED_STR:
    CORS_ALLOWED_ORIGINS = CORS_ALLOWED_STR.split(",")
else:
    CORS_ALLOWED_ORIGINS = []

# CSRF
CSRF_TRUSTED_ORIGINS_STR = os.getenv("CSRF_TRUSTED_ORIGINS")
if CSRF_TRUSTED_ORIGINS_STR:
    CSRF_TRUSTED_ORIGINS = CSRF_TRUSTED_ORIGINS_STR.split(",")
else:
    CSRF_TRUSTED_ORIGINS = [
        "http://localhost",
        "http://127.0.0.1",
        "http://0.0.0.0",
        "http://[::1]",
        "https://localhost",
        "https://127.0.0.1",
        "https://0.0.0.0",
        "https://[::1]",
    ]

# STATIC FILES
STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "static_files")
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Channels / WebSocket
ASGI_APPLICATION = "src.asgi.application"

# Channels / WebSocket configuration
REDIS_HOST = os.getenv("REDIS_HOST", "localhost")
REDIS_PORT = int(os.getenv("REDIS_PORT", 6379))

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(REDIS_HOST, REDIS_PORT)],
        },
    },
}
