# Generated by Django 5.2.4 on 2025-12-07 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='has_trial',
        ),
        migrations.RemoveField(
            model_name='user',
            name='stripe_client_id',
        ),
    ]
